<!--<img width=700px; src="../img/logoUPSayPlusCDS_990.png"> -->

<p style="margin-top: 3em; margin-bottom: 2em;"><b><big><big><big><big>Introdução ao módulo NumPy do Python</big></big></big></big></b></p>

# O que é um array (matriz) NumPy? 
O módulo NumPy é a base do módulo Pandas e de muitas outras packages python. O que torna o NumPy uma package tão notável é o tipo de dados (ndarray). ndarray significa array n-dimensional, que basicamente se parece com uma lista Python. No entanto, é muito mais rápido que uma lista Python comum. Uma lista Python pode conter tipos diferentes de dados, como números inteiros, sequências de caracteres, valores booleanos e até outras listas. Por outro lado, as matrizes NumPy podem conter apenas um tipo de dados e, portanto, não precisam verificar o tipo de tipo de dados para cada elemento único da matriz quando se realizam cálculos. Esse recurso faz do NumPy uma ótima ferramenta para pesquisas e projetos de análise de dados.

Antes de começar,verificar a versão do NumPy e Python:

In [1]:
# import numpy
import numpy as np

# importar módulo sys para verificar a versão do python
import sys 

# verificar versão de python e numpy
print('NumPy version:', np.__version__)
print('Python version',sys.version)

NumPy version: 1.16.3
Python version 3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 19:50:54) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]


# Como criar arrays NumPy

Existem várias formas de criar arrays (matrizes) no NumPy. 

In [2]:
# criar um array unidimensional
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
# Array de zeros
np.zeros(3)

array([0., 0., 0.])

In [4]:
# Array com valores = 1
np.ones(3)

array([1., 1., 1.])

In [5]:
# array de 3 inteiros aleatóreos entre 1 e 10
np.random.randint(1,10, 3)

array([9, 9, 1])

In [6]:
# criar um array linearmente "espaçado" 
np.linspace(0, 10, 5 )

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
# criar um array de 2 dimensões
np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# criar um array 3x4 com valores entre 0 e 1
np.random.random((3,4))

array([[7.75874132e-01, 2.71365286e-01, 3.52036830e-01, 5.24739878e-01],
       [1.11565843e-02, 4.81975722e-01, 4.37195728e-01, 7.10220203e-04],
       [3.90871106e-01, 7.68905818e-01, 9.58441174e-01, 8.63650449e-01]])

In [13]:
# criar arrays 1D e 2D, a e b
a = np.array([1,2,3])
b = np.random.randint(0,10, (3,3))

print("a = ", a)
print("b = ", b)

a =  [1 2 3]
b =  [[1 3 4]
 [6 1 8]
 [0 6 2]]


In [14]:
# adicionar valores 
a = np.append(a, 4)
a

array([1, 2, 3, 4])

In [16]:
# mostrar a forma e dimensão de arrays
print("Forma de a:", np.shape(a))
print("Forma de b:", np.shape(b))

print('Dimensão de a:', np.ndim(a))
print('Dimensão de b:', np.ndim(b))

Forma de a: (4,)
Forma de b: (3, 3)
Dimensãao de a: 1
Dimensão de b: 2


In [17]:
# número de elementos nos arrays 
print('Número de elementos em a:', np.size(a))
print('Número de elementos em b:', np.size(b))

Número de elementos em a: 4
Número de elementos em b: 9


# Indexação

In [18]:
# a é um array 1D, criado anteriormente
a

array([1, 2, 3, 4])

In [20]:
# b é um array 2D, também criado numa célula anterior deste notebook
b

array([[1, 3, 4],
       [6, 1, 8],
       [0, 6, 2]])

In [21]:
# obter o primeiro elemento de a 
# nota: estas duas instruções têm o mesmo resultado
print(a[0])
print(a[-4])

1
1


In [22]:
# obter o último elemento de a 
# nota: estas duas instruções têm o mesmo resultado
print(a[-1])
print(a[3])

4
4


In [17]:
# obter a primeira linha de b
# nota: estas duas instruções têm o mesmo resultado
print(b[0]) 
print(b[0,:])

[3 6 0]
[3 6 0]


In [23]:
# obter a segunda coluna de b
b[:,1]

array([3, 1, 6])

In [24]:
# para compreender outras técinas de indexação, crie 2 novos arrays: 
x = np.array(['a', 'b', 'c'])
y = np.array([['d','e','f'], 
              ['g', 'h', 'k']])

print(x)
print(y)

['a' 'b' 'c']
[['d' 'e' 'f']
 ['g' 'h' 'k']]


In [29]:
# indexação no array 1D
# obter o valor c no array x
ind = [2]
x[ind]
#teste a expressão seguinte e veja a diferença em relação
#ao anterior método de indexação:
#x[2]

array(['c'], dtype='<U1')

In [30]:
# indexação no array 2D 
# obter os valores e,h no array y
ind2 = [[0,1],[1]]
y[tuple(ind2)]

array(['e', 'h'], dtype='<U1')

# Slicing
Utilizar : para fazer slicing

In [31]:
# criar um array de interiros de 1 a 10
X = np.arange(1, 11, dtype=int)
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
# obter os primeiros 2 elementos de X 
X[:2]

array([1, 2])

In [24]:
# obter os elementos 3,4 e 5 
X[2:5]

array([3, 4, 5])

In [33]:
# obter os valores ímpares 
X[::2]

array([1, 3, 5, 7, 9])

In [26]:
# obter os valores pares
X[1::2]

array([ 2,  4,  6,  8, 10])

In [34]:
# criar array 2D
Y= np.arange(1,10).reshape(3,3)
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
# obter as duas primeiras linhas
Y[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
# obter a segunda e terceira coluna
Y[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [35]:
#obter os elementos 5 e 6
Y[1,1:]

array([5, 6])

# Funções universais (Ufuncs)

Permitir cálculo rápido em arrays NumPy.


In [36]:
# utilize o mesmo array que criou anteriormente
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
#calcular o valor máximo de X
np.max(X)

10

In [37]:
#média de valores em X
np.mean(X)

5.5

In [34]:
# obter a 4ª potência de cada elemento
np.power(X, 4)

array([    1,    16,    81,   256,   625,  1296,  2401,  4096,  6561, 10000])

In [38]:
# funções trigonométricas 
print(np.sin(X))
print(np.tan(X))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566  0.64836083]


In [39]:
# x2 + y2 = 1
np.square(np.sin(X)) + np.square(np.cos(X))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
# aplicam-se as mesmas reggras para arrays 2D
Y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
np.multiply(Y, 2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [41]:
# dividir Y em 3 sub-arrays
np.split(Y, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

# Broadcasting

 "Broadcasting" permite a utilização de funções universais e muitas outras operações em arrays de diferentes dimensões

In [39]:
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
# adicionar 5 a cada elemento
X + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
# ou 
np.add(X, 5)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
# criar novo array Z 
Z = np.arange(3)[:, np.newaxis]
Z

array([[0],
       [1],
       [2]])

In [43]:
# multiplicar Y por Z
np.multiply(Y, Z)

array([[ 0,  0,  0],
       [ 4,  5,  6],
       [14, 16, 18]])

# Ordenação, comparação e máscaras

In [48]:
# criar array de 10 elementos (aleatóreos) entre 1 e 5
x = np.random.randint(1,5, 10)
x

array([2, 3, 4, 3, 2, 2, 2, 3, 1, 4])

In [46]:
# criar um array (3,3) com elementos entre 1 e 5
y = np.random.randint(1,5, (3,3))
y

array([[3, 3, 1],
       [2, 4, 4],
       [4, 2, 2]])

In [49]:
# ordenar elementos no array x
np.sort(x)

array([1, 2, 2, 2, 2, 3, 3, 3, 4, 4])

In [47]:
# ordenar valores nas linhas
np.sort(y, axis=0)

array([[2, 2, 1],
       [3, 3, 2],
       [4, 4, 4]])

In [48]:
# sort values along the columns
np.sort(y, axis=1)

array([[1, 2, 4],
       [2, 4, 4],
       [4, 4, 4]])

In [50]:
# == , !=, < , >, >=, <= operações em arrays
#isto retorna um valor booleano
x > 3

array([False, False,  True, False, False, False, False, False, False,
        True])

In [50]:
# utilização de máscara para obter os valores de comparações
x[x>3]

array([4, 4])

In [51]:
# mais um exemplo 
x[(x <= 3) & (x>1)]

array([2, 3, 3, 2, 2, 2, 3])